# Generated by Django 5.2.6 on 2025-11-16 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officeAuth', '0004_officedepartment_leader_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inform', related_query_name='inform', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(related_name='inform', related_query_name='inform', to='officeAuth.officedepartment')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'inform',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='InformRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now_add=True)),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', related_query_name='reads', to='inform.inform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', related_query_name='reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知阅读',
                'verbose_name_plural': '通知阅读',
                'db_table': 'inform_read',
                'unique_together': {('inform', 'user')},
            },
        ),
    ]
