# Generated by Django 5.2.6 on 2025-11-23 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
        ('officeAuth', '0005_alter_officedepartment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inform', related_query_name='inform', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='content',
            field=models.TextField(verbose_name='通知内容'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='departments',
            field=models.ManyToManyField(related_name='inform', related_query_name='inform', to='officeAuth.officedepartment', verbose_name='可见部门'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='title',
            field=models.CharField(max_length=255, verbose_name='通知标题'),
        ),
        migrations.AlterField(
            model_name='inform',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='informread',
            name='inform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', related_query_name='reads', to='inform.inform', verbose_name='通知'),
        ),
        migrations.AlterField(
            model_name='informread',
            name='read_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='阅读时间'),
        ),
        migrations.AlterField(
            model_name='informread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', related_query_name='reads', to=settings.AUTH_USER_MODEL, verbose_name='阅读用户'),
        ),
    ]
