# Generated by Django 5.2.6 on 2025-10-29 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考勤类型名称')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='考勤标题')),
                ('request_content', models.TextField(verbose_name='考勤详情')),
                ('status', models.IntegerField(choices=[(1, '审核中'), (2, '已审批'), (3, '已拒绝')], default=1, verbose_name='考勤状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(verbose_name='请假开始时间')),
                ('end_time', models.DateTimeField(verbose_name='请假结束时间')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_content', models.TextField(blank=True, null=True, verbose_name='审批详情')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', related_query_name='attendance_requests', to=settings.AUTH_USER_MODEL, verbose_name='请假人')),
                ('responser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_responsers', related_query_name='attendance_responsers', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('attendance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', related_query_name='attendance', to='officeAttendance.attendancetype', verbose_name='考勤类型')),
            ],
            options={
                'verbose_name': '考勤详情',
                'verbose_name_plural': '考勤详情',
                'db_table': 'attendance',
            },
        ),
    ]
