# Generated by Django 5.2.6 on 2025-10-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeAttendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence_Status',
            new_name='Attendance_Status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='requester_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='请假人名称'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='responser_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='审批人名称'),
        ),
    ]
