# Generated by Django 5.2.6 on 2025-11-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeAttendance', '0002_rename_attendence_status_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-create_time'], 'verbose_name': '考勤详情', 'verbose_name_plural': '考勤详情'},
        ),
    ]
