# Generated by Django 5.2.6 on 2025-10-25 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField(max_length=500)),
                ('leader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_department', related_query_name='leader_department', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_department', related_query_name='manager_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='officeuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_department', related_query_name='users_department', to='officeAuth.officedepartment'),
        ),
    ]
