# Generated by Django 5.2.6 on 2025-10-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeAuth', '0002_officedepartment_officeuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeuser',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
