# Generated by Django 5.2.6 on 2025-10-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeAuth', '0003_alter_officeuser_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='officedepartment',
            name='leader_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officedepartment',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
