# Generated by Django 5.2.6 on 2025-11-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeAuth', '0004_officedepartment_leader_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officedepartment',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='status',
            field=models.IntegerField(choices=[(2, '已锁定'), (1, '已激活'), (0, '未激活')], default=0),
        ),
    ]
